## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/dieliste"
  to = "https://docs.google.com/spreadsheets/d/1OVWClUuYn7EL9XNTiJja63HpRUyyWvQXtlYn02ywmK8"
  status = 200
  force = true # COMMENT: ensure that we always redirect
[[redirects]]
  from = "/brettspielwochenende"
  to = "/20261002_brettspielwochenende"
